# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

gym_1 = Gym.create(name: "AMC Pankration", location: "Kirkland, WA", owner: "Matt Hume", image_url: "http://www.mmawizard.com/amc/files/wizard-crest.jpg", description: "AMC Kickboxing & Pankration offers classes and training for men, women and children...non-competitors and competitors. Our classes offer the world's best instruction in boxing, kickboxing, submission wrestling, pankration, Brazilian Jiu Jitsu and MMA fighting. These classes are designed to build your technique and conditioning in a non-threatening, safe and fun environment. AMC's world renowned fighter's training has developed the world's most well rounded professional world champion fighters in all aspects of combat. ")

gym_1.fighters.create(name: "Demetrious Johnson", age: 31, weight_class: "Flyweight", hometown: "Madisonville, KY", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Demetrious_Johnson.jpg/200px-Demetrious_Johnson.jpg", description: "An American wrestler and mixed martial artist. He is the first and the current Flyweight Champion of the Ultimate Fighting Championship (UFC). He currently holds the record for longest championship reign at eleven title defenses. Known for his quick striking and elusive movement, Johnson has also landed the most takedowns in UFC flyweight history and holds the record for the latest finish in UFC history with a submission win at 4:59 of the fifth round against Kyoji Horiguchi. He is also the only UFC fighter to record over 10 takedowns in three different fights.")

gym_1.fighters.create(name: "Tim Boetsch", age: 36, weight_class: "Middleweight", hometown: "Linconville, ME", image_url: "http://www.sherdog.com/image_crop/200/300/_images/fighter/20140413031004_IMG_4323.JPG", description: "An American professional mixed martial artist currently fighting in the Middleweight division of the Ultimate Fighting Championship.[5] In addition to the UFC, Boetsch has formerly competed as an alternate for the New York Pitbulls in the International Fight League and King of the Cage.[6] He holds victories over former UFC welterweight champion Johny Hendricks and former Bellator middleweight champion Hector Lombard.[7] As of July 21, 2017, he is ranked #13 in official UFC Middleweight rankings.")

gym_1.fighters.create(name: "Caros Fedor", age: 33, weight_class: "Lightweight", hometown: "Shoreline, WA", image_url: "http://www.sherdog.com/image_crop/200/300/_images/fighter/20130913105341_caros_fodor.JPG", description: "An American professional mixed martial artist currently competing in ONE FC's lightweight division. He has also competed for the UFC, Strikeforce, and King of the Cage.")

gym_2 = Gym.create(name: "American Kickboxing Academy", location: "San Jose, CA", owner: "Javier Mendez", image_url: "https://images.activityhero.com/35394/original/3cdbf627-8666-4104-ad3d-e2fb8a599141.png", description: "A martial arts gym Based in San Jose, California. It is one of the pioneering schools of mixed martial arts (MMA). AKA headquarters is located in South San Jose. In 2014 AKA opened AKA Thailand Gym in Phuket Thailand. Prominent trainers include Brazilian Jiu-Jitsu master Leandro Vieira, Bob Cook, Derek Yuen, Javier Mendez, and Andy Fong. Within the facility, Muay Thai, Brazilian Jiu-jitsu, Wrestling and Boxing classes are taught. Additional programs include conditioning and circuit training with TRX Suspension and Combat Circuit. American Kickboxing Academy is one of the top professional MMA training camps.")

gym_2.fighters.create(name: "Daniel Cormier", age: 38, weight_class: "Light Heavyweight", hometown: "Lafayette, LA", image_url: "http://www.sherdog.com/image_crop/200/300/_images/fighter/20140213015944_daniel_cormier.JPG", description: "An American mixed martial artist and former Olympic wrestler. He is the current UFC Light Heavyweight Champion, and is ranked as the sixth best pound-for-pound fighter in the UFC." )

gym_2.fighters.create(name: "Cain Velasquez", age: 35, weight_class: "Heavyweight", hometown: "Salinas, CA", image_url: "http://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335654.png&w=350&h=254", description: "An American mixed martial artist. He is a former two-time UFC Heavyweight Champion, with victories over Brock Lesnar and Junior dos Santos. As of September 28, 2017, he is the 3rd ranked heavyweight in the UFC's official rankings")
